// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAuOyw7Eqsq0M-pxbm8r3-4NxkDhajF3_c',
    appId: '1:487029278157:web:69595ccf1e87855fafb084',
    messagingSenderId: '487029278157',
    projectId: 'host-test-back-end',
    authDomain: 'host-test-back-end.firebaseapp.com',
    storageBucket: 'host-test-back-end.appspot.com',
    measurementId: 'G-02QWCV3ZZ6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAIsNl0g9rLtKRgyAhXrlvTAI2v9g5a3gw',
    appId: '1:487029278157:android:92c0f8152f184eafafb084',
    messagingSenderId: '487029278157',
    projectId: 'host-test-back-end',
    storageBucket: 'host-test-back-end.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAlmV2bvmQAW_9yquBV5Jw33pYwJOlJiOQ',
    appId: '1:487029278157:ios:c84d192e57a25e57afb084',
    messagingSenderId: '487029278157',
    projectId: 'host-test-back-end',
    storageBucket: 'host-test-back-end.appspot.com',
    iosClientId: '487029278157-75otsil10sfqr8nvq68qt3vvvnimvrkm.apps.googleusercontent.com',
    iosBundleId: 'com.codeartistry.fluttershare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAlmV2bvmQAW_9yquBV5Jw33pYwJOlJiOQ',
    appId: '1:487029278157:ios:aadc20a8d87a896aafb084',
    messagingSenderId: '487029278157',
    projectId: 'host-test-back-end',
    storageBucket: 'host-test-back-end.appspot.com',
    iosClientId: '487029278157-bp1g7s981cqmo3hasmf629dvln8hff1k.apps.googleusercontent.com',
    iosBundleId: 'app.host-social',
  );
}
